### ISSUE TITLE
Reset information on combat reset/ wipe

### ISSUE THREAD

**Issue by abranon** [rootdarkarchon/OhGeeCD#3]
Right now the information provided carries on as normal despite wiping so the timers are off, not a super big issue so feel free to backlog it!

**Comment by rootdarkarchon** [comment]
Oh yeah i noticed this as well and i know why. It used to work but one change of mine broke it. I'll fix it asap.

**Comment by rootdarkarchon** [comment]
Should be fixed in 0.0.13
