### ISSUE TITLE
More display options

### ISSUE THREAD

**Issue by codyhatch** [rootdarkarchon/OhGeeCD#4]
I'd love it if there was the option to either:

1) Diplay an oGCD while it was on cooldown (but not otherwise, so you just see the CD of skills that you can't use yet)
2) Display an oGCD while it is available (but not otherwise, so you just see a display of the skills you CAN currently use)

Currently it seems skills always show both when on and off cooldown.

**Comment by rootdarkarchon** [comment]
Can do, should this be settable per ogcd group or per ogcd?

Actually it makes most sense on a per ogcd basis so I'll do that. I'm currently busy with another project but this should be an easy addition.

**Comment by rootdarkarchon** [comment]
Added and released as 0.0.15 per OGCD action. Let me know if this works for you.

**Comment by codyhatch** [comment]
That's *perfect*! Super useful for me. :) Thanks for the fast addition.
